/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trojuhelnik.pocitani;

import static java.lang.Math.sqrt;
import javax.print.attribute.standard.Sides;

/**
 *
 * @author Sonny
 */
public class Trojuhelnik extends javax.swing.JFrame {

    /**
     * Creates new form Trojuhelnik
     */
    public Trojuhelnik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Ay = new javax.swing.JTextField();
        Ax = new javax.swing.JTextField();
        By = new javax.swing.JTextField();
        Bx = new javax.swing.JTextField();
        Cy = new javax.swing.JTextField();
        Cx = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SendText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(581, 618));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\theso\\OneDrive\\Plocha\\1triangle.png")); // NOI18N

        Ay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Ay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ay.setToolTipText("");
        Ay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyActionPerformed(evt);
            }
        });
        Ay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AyKeyTyped(evt);
            }
        });

        Ax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Ax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ax.setToolTipText("");
        Ax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AxActionPerformed(evt);
            }
        });
        Ax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AxKeyTyped(evt);
            }
        });

        By.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        By.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        By.setToolTipText("");
        By.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ByActionPerformed(evt);
            }
        });
        By.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ByKeyTyped(evt);
            }
        });

        Bx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Bx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Bx.setToolTipText("");
        Bx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BxActionPerformed(evt);
            }
        });
        Bx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BxKeyTyped(evt);
            }
        });

        Cy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cy.setToolTipText("");
        Cy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CyActionPerformed(evt);
            }
        });
        Cy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CyKeyTyped(evt);
            }
        });

        Cx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cx.setToolTipText("");
        Cx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxActionPerformed(evt);
            }
        });
        Cx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CxKeyTyped(evt);
            }
        });

        jButton1.setText("Vypočítat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("C[");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A[");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("]");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("B[");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("]");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("]");

        SendText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SendText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SendText, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(Cy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(Ay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(By, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SendText, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cx, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cy, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Ax, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Ay, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Bx, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(By, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AyActionPerformed

    private void AxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AxActionPerformed

    private void ByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ByActionPerformed

    private void CyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CyActionPerformed

    private void CxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       /*
        Zadání:
        Navrhněte algoritmus, který určí, jestli je ze zadaných bodů možné sestrojit trojúhelník. Body budou zadávány pozicí v kartézské soustavě souřadnic (souřadnicová soustava „0xy“ – stačí v rovině). Pozice bodů budou určeny celočíselně.


        Získaní inputu | Převod na double
        */
       
        //Souřadnice A
            double ax = Double.parseDouble(Ax.getText());
            double ay = Double.parseDouble(Ay.getText());
        
        //Souřadnice B    
	    double bx = Double.parseDouble(Bx.getText()); 
            double by = Double.parseDouble(By.getText());  
            
        //Souřadnice C    
	    double cx =  Double.parseDouble(Cx.getText());  
            double cy  = Double.parseDouble(Cy.getText()); 
            
            double staticNumber = 2;

            
          /*
            Počítaní Základny C
            */  
          
            double sideC = (Math.sqrt(Math.pow((cx-ax), staticNumber) + Math.pow((cy-ay), staticNumber)))/2; 

            /*
            Počítaní Odvěsny B
            */
            
            double sideB = Math.sqrt(Math.pow((bx-ax), staticNumber) + Math.pow((by-ay), staticNumber));
     
            /*
            Pythagorova Věta
            */
                             
            double resultPyth = Math.sqrt((Math.pow(sideB, staticNumber)) - (Math.pow(sideC, staticNumber))); // na druhou

            /*
            Obash
            */
            double content = 0.5*sideC*resultPyth;
            
            System.out.println("Obsah je -> "+content);
            
            /*
            Pokud Obsah neni roven 0 jedná se o trojúhelník
            */
            
            if (content == 0){
                SendText.setText("Nejedná se o Trojúhelník");
            }
            else if (content != 0){
                SendText.setText("Toto je Trojúhelník");
            } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BxActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped

    }//GEN-LAST:event_formKeyTyped

    private void CxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CxKeyTyped
        char input = evt.getKeyChar(); //uloží do proměnné při každém zadaní klavesy danou hodnotu
        if(!Character.isDigit(input)){ // pokud neni roven čislu tak event zakaze zapsat hodnotu
           evt.consume();
           }
    }//GEN-LAST:event_CxKeyTyped

    private void CyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CyKeyTyped
        char input = evt.getKeyChar(); //uloží do proměnné při každém zadaní klavesy danou hodnotu
        if(!Character.isDigit(input)){ // pokud neni roven čislu tak event zakaze zapsat hodnotu
           evt.consume();
           }
    }//GEN-LAST:event_CyKeyTyped

    private void AxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AxKeyTyped
        char input = evt.getKeyChar(); //uloží do proměnné při každém zadaní klavesy danou hodnotu
        if(!Character.isDigit(input)){ // pokud neni roven čislu tak event zakaze zapsat hodnotu
           evt.consume();
           }
    }//GEN-LAST:event_AxKeyTyped

    private void AyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AyKeyTyped
        char input = evt.getKeyChar(); //uloží do proměnné při každém zadaní klavesy danou hodnotu
        if(!Character.isDigit(input)){ // pokud neni roven čislu tak event zakaze zapsat hodnotu
           evt.consume();
           }
    }//GEN-LAST:event_AyKeyTyped

    private void BxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BxKeyTyped
        char input = evt.getKeyChar(); //uloží do proměnné při každém zadaní klavesy danou hodnotu
        if(!Character.isDigit(input)){ // pokud neni roven čislu tak event zakaze zapsat hodnotu
           evt.consume();
           }
    }//GEN-LAST:event_BxKeyTyped

    private void ByKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ByKeyTyped
        char input = evt.getKeyChar(); //uloží do proměnné při každém zadaní klavesy danou hodnotu
        if(!Character.isDigit(input)){ // pokud neni roven čislu tak event zakaze zapsat hodnotu
           evt.consume();
           }
    }//GEN-LAST:event_ByKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trojuhelnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trojuhelnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trojuhelnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trojuhelnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trojuhelnik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ax;
    private javax.swing.JTextField Ay;
    private javax.swing.JTextField Bx;
    private javax.swing.JTextField By;
    private javax.swing.JTextField Cx;
    private javax.swing.JTextField Cy;
    private javax.swing.JLabel SendText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
