/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

import java.util.Random;

/**
 *
 * @author Administrator
 */
public class deset extends javax.swing.JFrame {

    /**
     * Creates new form deset
     */
    public deset() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jButton1)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jButton1)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {  
        /*
        Zadani
        Navrhněte algoritmus, který v poli 10 × 10 vypočítá a vypíše průměry hodnot na uhlopříčkách od levé horní buňky k pravé dolní (hlavní uhlopříčka) a od pravé horní buňky k levé dolní (vedlejší uhlopříčka). D
        */                                       

        // Obecné Proměnné
        Random rand = new Random();
        int pole[][] = new int[10][10];
        
        //Naplnění pole random hodnotama
        for(int i = 0; i < pole.length; i++){
            for(int j = 0; j < pole.length; j++){
                pole[i][j] = rand.nextInt(10);
            }
        }
        
    /*
        Levá Úhlopríčka
    */
        
        //Promenné pro levou úhlopříčku
        int levaUhlopricka = 0;
        int prumerLeveUhlopricky = 0;
        
        //Výpočet levé úhlopříčky
        for(int i = 0; i < pole.length; i++){
            prumerLeveUhlopricky += pole[i][levaUhlopricka];
            levaUhlopricka++; 
        }
    /*
        Pravá Úhlopríčka
    */
        
        //Promenné pro pravou úhlopříčku
        int pravaUhlopricka = 9;
        int prumerPraveUhlopricky = 0;
        
        //Výpočet pravé úhlopříčky
        for(int i = 0; i < pole.length; i++){
            prumerPraveUhlopricky += pole[i][pravaUhlopricka];
            pravaUhlopricka--;         
        }        
            //Vypis hodnot z pole
            for(int a = 0; a < pole.length; a++){
                for(int b = 0; b < pole.length; b++){
                    System.out.print(pole[a][b]+ " "); 
                }
                System.out.println(" ");
            }
            
            //Výpis Průměrů
            System.out.println("Prumer leve uhlopricky je "+prumerLeveUhlopricky/10);
            System.out.println("Prumer prave uhlopricky je "+prumerPraveUhlopricky/10);
            
            if(prumerLeveUhlopricky > prumerPraveUhlopricky){
                System.out.println("Leva uhlopricka ma vetsi prumer nez prava uhlopricka");
            }
            else{
                System.out.println("Leva uhlopricka ma mensi prumer nez prava uhlopricka");
            }

        
        
        
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    // End of variables declaration                   
}
