/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;

import java.util.Random;

/**
 *
 * @author Administrator
 */
public class SestFrame extends javax.swing.JFrame {

    /**
     * Creates new form SestFrame
     */
    public SestFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton1)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
            Random rand = new Random();
            int[][] pole = new int[5][5];
              
            
for(int i = 0; i < pole.length; i++){
    for(int j = 0; j < pole.length; j++){
        // Generování náhodné pozice v poli
        int randomIndexI = rand.nextInt(pole.length);
        int randomIndexJ = rand.nextInt(pole.length);
        
        // Pokud je pozice v poli prázdná, přiřaď náhodné číslo
        if(pole[randomIndexI][randomIndexJ] == 0){
            pole[randomIndexI][randomIndexJ] = rand.nextInt(9);
        }
        // Pokud není pozice prázdná, opakujt cyklus pro novou pozici
        else{
            j--;
        }
    }
}
 
            //hledaní max hodnoty
            int max = pole[0][0];
            int MaxSouradniceX = 0;
            int MaxSouradniceY = 0;
            
            for(int c = 0; c < pole.length; c++){
                for(int d = 0; d < pole.length; d++){
                    if(pole[c][d] > max){
                        max = pole[c][d];
                        MaxSouradniceX = c+1;
                        MaxSouradniceY = d+1;
                    }
                }
            }
            
            //hledaní min hodnoty
            int min = pole[0][0];
            int MinSouradniceX = 0;
            int MinSouradniceY = 0;
            
            for(int c = 0; c < pole.length; c++){
                for(int d = 0; d < pole.length; d++){
                    if(pole[c][d] < min){
                        min = pole[c][d];
                        MinSouradniceY = c+1;
                        MinSouradniceX = d+1;                        
                    }
                }
            }

            //Výpis hodnot z pole
            for(int a = 0; a < pole.length; a++){
                for(int b = 0; b < pole.length; b++){
                    System.out.print(pole[a][b]+ " "); 
                }
                System.out.println(" ");
            }       
                        
             System.out.println("Nejvetsi hodnota je "+max+" SOURADNICE Y "+MaxSouradniceY+" X "+MaxSouradniceX);
             System.out.println("Nejmesi hodnota je "+min+" SOURADNICE Y "+MinSouradniceY+" X "+MinSouradniceX);     

    
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    // End of variables declaration                   
}
