/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;

import java.util.Random;

/**
 *
 * @author Administrator
 */
public class sedmyproejtk extends javax.swing.JFrame {

    /**
     * Creates new form sedmyproejtk
     */
    public sedmyproejtk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButton1)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        /*
        Zadani
        Navrhněte algoritmus, který v poli 10 × 10 určí počet hodnot 0, 1, 2, 3 … 9. Pole naplňte náhodnými celými čísly z intervalu <0; 9>.
        */
        Random rand = new Random();
        int pole[][] = new int[10][10];
        
        //nahrani hodnot
        for(int i = 0; i < pole.length; i++ ){
            for(int j = 0; j < pole.length; j++){
                pole[i][j] = rand.nextInt(10);
            }
        }
        //Hodnoty pro záznam počtu daných prvků
        int count;
        int one = 0;
        int two = 0;
        int three = 0;
        int four = 0;
        int five = 0;
        int six = 0;
        int seven = 0;
        int eight = 0;
        int nine = 0;
        int ten = 0;
        
        for(int i = 0; i < pole.length; i++ ){
            for(int j = 0; j < pole.length; j++){
                switch (pole[i][j]){
                    case 1: count = 1;
                        one++;
                        break;
                    case 2: count = 2;
                        two++;
                        break;
                    case 3: count = 3;
                        three++;
                        break;
                    case 4: count = 4;
                        four++;
                        break;
                    case 5: count = 5;
                        five++;
                        break;
                    case 6: count = 6;
                        six++;
                        break;
                    case 7: count = 7;
                        seven++;
                        break;
                    case 8: count = 8;
                        eight++;
                        break;
                    case 9: count = 9;
                        nine++;
                        break;                       
                }
                  
              }  
            }
        System.out.println("1."+one+"x "+"2."+two+"x "+"3."+three+"x "+"4."+four+"x "+"5."+five+"x "+"6."+six+"x "+"7."+seven+"x "+"8."+eight+"x "+"9."+nine+"x ");
          
        //vypis
        for(int i = 0; i < pole.length; i++ ){
            for(int j = 0; j < pole.length; j++){
                System.out.print(pole[i][j]+" ");
            }
            System.out.println(" ");
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sedmyproejtk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sedmyproejtk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sedmyproejtk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sedmyproejtk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sedmyproejtk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    // End of variables declaration                   
}
