/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.util.Random;

/**
 *
 * @author Administrator
 */
public class devet extends javax.swing.JFrame {

    /**
     * Creates new form devet
     */
    public devet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jButton1)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jButton1)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        /*
        Zadani
        Navrhněte algoritmus, který bude pracovat se 3 poli 5 × 5. První a druhé pole naplní náhodnými hodnotami 0 nebo 1. Třetí pole naplní hodnotami tak, že pokud na stejných souřadnicích prvního a druhého pole bude hodnota 0 (nula), zapíše se do třetího pole hodnota „N“; pokud bude na stejných souřadnicích prvního a druhého pole hodnota 1, zapíše se do třetího pole hodnota „A“. Pokud budou hodnoty na stejných souřadnicích prvního a druhého pole rozdílné, zapíše se do třetího pole hodnota „X“.
        */
        
        Random rand = new Random();
        
        //Inicializace Polí 
        int poleFirst[][] = new int[5][5];
        int poleSecond[][] = new int[5][5];
        String poleThird[][] = new String[5][5];
        
        
        //Generování 0 a 1 do polí
        for(int i = 0; i < poleFirst.length; i++){
            for(int j = 0; j < poleFirst.length; j++){
                poleFirst[i][j] = rand.nextInt(2);
                poleSecond[i][j] = rand.nextInt(2);
            }
        }
        
        //hledaní hodnot
        for(int i = 0; i < poleFirst.length; i++){
            for(int j = 0; j < poleFirst.length; j++){
                if( poleFirst[i][j] == 0 && poleSecond[i][j] == 0 ){
                 poleThird[i][j] = "N";   
                }
                else if( poleFirst[i][j] == 1 && poleSecond[i][j] == 1 ){
                    poleThird[i][j] = "A";   
                }
                else{
                    poleThird[i][j] = "X";   
                }
            }
        }        
        
        
        

        
            //Výpis hodnot z pole 1
            for(int a = 0; a < poleFirst.length; a++){
                for(int b = 0; b < poleFirst.length; b++){
                    System.out.print(poleFirst[a][b]+ " "); 
                }
                System.out.println(" ");
            }
            
            System.out.println(" ");
            
            //Výpis hodnot z pole 2
            for(int a = 0; a < poleSecond.length; a++){
                for(int b = 0; b < poleSecond.length; b++){
                    System.out.print(poleSecond[a][b]+ " "); 
                }
                System.out.println(" ");
            }
            
            System.out.println(" ");

            
            //Výpis hodnot z pole 3
            for(int a = 0; a < poleThird.length; a++){
                for(int b = 0; b < poleThird.length; b++){
                    System.out.print(poleThird[a][b]+ " "); 
                }
                System.out.println(" ");
            }             
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(devet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(devet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(devet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(devet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new devet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    // End of variables declaration                   
}
